baseURL = "https://williammueller.com/"
languageCode = "en"
defaultContentLanguage = "en"
title = "Stip"
theme = "stip"
disableKinds = ["page", "section", "taxonomy", "taxonomyTerm"]

[Author]
    name = "William Mueller"
#    bio = "bio"

[params]

    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://www.linkedin.com/in/willpmueller/"
