## Basic Configuration

baseurl = "https://williammueller.com" 
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"


author = "William Mueller"
title = "William Mueller"

theme = "hugo-goa"

## Hugo Built-in Features
## disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
## googleAnalytics = "XYZ"
enableRobotsTXT = true

## Site Settings
[params]
author = "William Mueller"
intro = "intro"
description = "Description <br/> more description"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"


## Site Meta Settings
[params.meta]
description = "William Mueller"
keywords = ""

## Social Accounts
[params.social]
linkedin = "<willpmueller>"

## Extras
[params.extra]
copyright = "© 2021. William Mueller."
poweredby = false
hightlightjs = false
socialmarkup = false
toc = false
displayrssicon = false

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"
